[{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/api/generation/[id]/route.ts",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 15,
	"startColumn": 5,
	"endLineNumber": 15,
	"endColumn": 7,
	"modelVersionId": 11,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'field' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 216,
	"startColumn": 24,
	"endLineNumber": 216,
	"endColumn": 29,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'value' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 216,
	"startColumn": 31,
	"endLineNumber": 216,
	"endColumn": 36,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'field' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 217,
	"startColumn": 24,
	"endLineNumber": 217,
	"endColumn": 29,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'item' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 217,
	"startColumn": 31,
	"endLineNumber": 217,
	"endColumn": 35,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7053",
	"severity": 8,
	"message": "Element implicitly has an 'any' type because expression of type 'any' can't be used to index type '{ industry: string; industryOther: string; businessModel: string; businessName: string; businessDescription: string; businessTagline: string; differentiator: string; businessStage: string; ... 30 more ...; additionalNotes: string; }'.",
	"source": "ts",
	"startLineNumber": 219,
	"startColumn": 19,
	"endLineNumber": 219,
	"endColumn": 30,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'i' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 220,
	"startColumn": 66,
	"endLineNumber": 220,
	"endColumn": 67,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'items' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 286,
	"startColumn": 25,
	"endLineNumber": 286,
	"endColumn": 30,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'selected' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 286,
	"startColumn": 32,
	"endLineNumber": 286,
	"endColumn": 40,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'onSelect' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 286,
	"startColumn": 42,
	"endLineNumber": 286,
	"endColumn": 50,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'item' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 288,
	"startColumn": 18,
	"endLineNumber": 288,
	"endColumn": 22,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'items' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 311,
	"startColumn": 26,
	"endLineNumber": 311,
	"endColumn": 31,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'selected' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 311,
	"startColumn": 33,
	"endLineNumber": 311,
	"endColumn": 41,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'onToggle' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 311,
	"startColumn": 43,
	"endLineNumber": 311,
	"endColumn": 51,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'item' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 313,
	"startColumn": 18,
	"endLineNumber": 313,
	"endColumn": 22,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'label' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 337,
	"startColumn": 24,
	"endLineNumber": 337,
	"endColumn": 29,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'required' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 337,
	"startColumn": 31,
	"endLineNumber": 337,
	"endColumn": 39,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'placeholder' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 337,
	"startColumn": 41,
	"endLineNumber": 337,
	"endColumn": 52,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'value' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 337,
	"startColumn": 54,
	"endLineNumber": 337,
	"endColumn": 59,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'onChange' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 337,
	"startColumn": 61,
	"endLineNumber": 337,
	"endColumn": 69,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'label' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 347,
	"startColumn": 23,
	"endLineNumber": 347,
	"endColumn": 28,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'required' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 347,
	"startColumn": 30,
	"endLineNumber": 347,
	"endColumn": 38,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'placeholder' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 347,
	"startColumn": 40,
	"endLineNumber": 347,
	"endColumn": 51,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'value' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 347,
	"startColumn": 53,
	"endLineNumber": 347,
	"endColumn": 58,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'onChange' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 347,
	"startColumn": 60,
	"endLineNumber": 347,
	"endColumn": 68,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'hint' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 347,
	"startColumn": 80,
	"endLineNumber": 347,
	"endColumn": 84,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'children' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 358,
	"startColumn": 27,
	"endLineNumber": 358,
	"endColumn": 35,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'value' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 362,
	"startColumn": 20,
	"endLineNumber": 362,
	"endColumn": 25,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'onChange' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 362,
	"startColumn": 27,
	"endLineNumber": 362,
	"endColumn": 35,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 386,
	"startColumn": 21,
	"endLineNumber": 386,
	"endColumn": 22,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 398,
	"startColumn": 21,
	"endLineNumber": 398,
	"endColumn": 22,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 407,
	"startColumn": 49,
	"endLineNumber": 407,
	"endColumn": 50,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 410,
	"startColumn": 56,
	"endLineNumber": 410,
	"endColumn": 57,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "2741",
	"severity": 8,
	"message": "Property 'required' is missing in type '{ label: string; placeholder: string; value: string; onChange: (v: any) => void; }' but required in type '{ label: any; required: any; placeholder: any; value: any; onChange: any; type?: string | undefined; }'.",
	"source": "ts",
	"startLineNumber": 412,
	"startColumn": 8,
	"endLineNumber": 412,
	"endColumn": 17,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 413,
	"startColumn": 52,
	"endLineNumber": 413,
	"endColumn": 53,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "2739",
	"severity": 8,
	"message": "Type '{ label: string; placeholder: string; value: string; onChange: (v: any) => void; }' is missing the following properties from type '{ label: any; required: any; placeholder: any; value: any; onChange: any; rows?: number | undefined; hint: any; }': required, hint",
	"source": "ts",
	"startLineNumber": 414,
	"startColumn": 8,
	"endLineNumber": 414,
	"endColumn": 16,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 415,
	"startColumn": 51,
	"endLineNumber": 415,
	"endColumn": 52,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 425,
	"startColumn": 21,
	"endLineNumber": 425,
	"endColumn": 22,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'id' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 474,
	"startColumn": 21,
	"endLineNumber": 474,
	"endColumn": 23,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "2739",
	"severity": 8,
	"message": "Type '{ label: string; placeholder: string; value: string; onChange: (v: any) => void; }' is missing the following properties from type '{ label: any; required: any; placeholder: any; value: any; onChange: any; rows?: number | undefined; hint: any; }': required, hint",
	"source": "ts",
	"startLineNumber": 477,
	"startColumn": 10,
	"endLineNumber": 477,
	"endColumn": 18,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 478,
	"startColumn": 58,
	"endLineNumber": 478,
	"endColumn": 59,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type 'string' is not assignable to parameter of type 'never'.",
	"source": "ts",
	"startLineNumber": 510,
	"startColumn": 61,
	"endLineNumber": 510,
	"endColumn": 65,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'id' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 564,
	"startColumn": 21,
	"endLineNumber": 564,
	"endColumn": 23,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'i' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 572,
	"startColumn": 28,
	"endLineNumber": 572,
	"endColumn": 29,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'field' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 572,
	"startColumn": 31,
	"endLineNumber": 572,
	"endColumn": 36,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'val' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 572,
	"startColumn": 38,
	"endLineNumber": 572,
	"endColumn": 41,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'i' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 576,
	"startColumn": 28,
	"endLineNumber": 576,
	"endColumn": 29,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "2741",
	"severity": 8,
	"message": "Property 'required' is missing in type '{ label: string; placeholder: string; value: string; onChange: (v: any) => void; }' but required in type '{ label: any; required: any; placeholder: any; value: any; onChange: any; type?: string | undefined; }'.",
	"source": "ts",
	"startLineNumber": 605,
	"startColumn": 10,
	"endLineNumber": 605,
	"endColumn": 19,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 606,
	"startColumn": 49,
	"endLineNumber": 606,
	"endColumn": 50,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 609,
	"startColumn": 62,
	"endLineNumber": 609,
	"endColumn": 63,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7053",
	"severity": 8,
	"message": "Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ industry: string; industryOther: string; businessModel: string; businessName: string; businessDescription: string; businessTagline: string; differentiator: string; businessStage: string; ... 30 more ...; additionalNotes: string; }'.\n  No index signature with a parameter of type 'string' was found on type '{ industry: string; industryOther: string; businessModel: string; businessName: string; businessDescription: string; businessTagline: string; differentiator: string; businessStage: string; ... 30 more ...; additionalNotes: string; }'.",
	"source": "ts",
	"startLineNumber": 682,
	"startColumn": 42,
	"endLineNumber": 682,
	"endColumn": 57,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7053",
	"severity": 8,
	"message": "Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ industry: string; industryOther: string; businessModel: string; businessName: string; businessDescription: string; businessTagline: string; differentiator: string; businessStage: string; ... 30 more ...; additionalNotes: string; }'.\n  No index signature with a parameter of type 'string' was found on type '{ industry: string; industryOther: string; businessModel: string; businessName: string; businessDescription: string; businessTagline: string; differentiator: string; businessStage: string; ... 30 more ...; additionalNotes: string; }'.",
	"source": "ts",
	"startLineNumber": 685,
	"startColumn": 38,
	"endLineNumber": 685,
	"endColumn": 53,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7053",
	"severity": 8,
	"message": "Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ industry: string; industryOther: string; businessModel: string; businessName: string; businessDescription: string; businessTagline: string; differentiator: string; businessStage: string; ... 30 more ...; additionalNotes: string; }'.\n  No index signature with a parameter of type 'string' was found on type '{ industry: string; industryOther: string; businessModel: string; businessName: string; businessDescription: string; businessTagline: string; differentiator: string; businessStage: string; ... 30 more ...; additionalNotes: string; }'.",
	"source": "ts",
	"startLineNumber": 686,
	"startColumn": 81,
	"endLineNumber": 686,
	"endColumn": 96,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 709,
	"startColumn": 51,
	"endLineNumber": 709,
	"endColumn": 52,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "18047",
	"severity": 8,
	"message": "'e.target.files' is possibly 'null'.",
	"source": "ts",
	"startLineNumber": 713,
	"startColumn": 90,
	"endLineNumber": 713,
	"endColumn": 104,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'name' does not exist on type 'never'.",
	"source": "ts",
	"startLineNumber": 716,
	"startColumn": 154,
	"endLineNumber": 716,
	"endColumn": 158,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "2741",
	"severity": 8,
	"message": "Property 'required' is missing in type '{ label: string; placeholder: string; value: string; onChange: (v: any) => void; type: string; }' but required in type '{ label: any; required: any; placeholder: any; value: any; onChange: any; type?: string | undefined; }'.",
	"source": "ts",
	"startLineNumber": 732,
	"startColumn": 10,
	"endLineNumber": 732,
	"endColumn": 19,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 732,
	"startColumn": 110,
	"endLineNumber": 732,
	"endColumn": 111,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "2741",
	"severity": 8,
	"message": "Property 'required' is missing in type '{ label: string; placeholder: string; value: string; onChange: (v: any) => void; type: string; }' but required in type '{ label: any; required: any; placeholder: any; value: any; onChange: any; type?: string | undefined; }'.",
	"source": "ts",
	"startLineNumber": 733,
	"startColumn": 10,
	"endLineNumber": 733,
	"endColumn": 19,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 733,
	"startColumn": 110,
	"endLineNumber": 733,
	"endColumn": 111,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "2741",
	"severity": 8,
	"message": "Property 'required' is missing in type '{ label: string; placeholder: string; value: string; onChange: (v: any) => void; }' but required in type '{ label: any; required: any; placeholder: any; value: any; onChange: any; type?: string | undefined; }'.",
	"source": "ts",
	"startLineNumber": 735,
	"startColumn": 8,
	"endLineNumber": 735,
	"endColumn": 17,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 735,
	"startColumn": 124,
	"endLineNumber": 735,
	"endColumn": 125,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "2741",
	"severity": 8,
	"message": "Property 'required' is missing in type '{ label: string; placeholder: string; value: string; onChange: (v: any) => void; }' but required in type '{ label: any; required: any; placeholder: any; value: any; onChange: any; type?: string | undefined; }'.",
	"source": "ts",
	"startLineNumber": 736,
	"startColumn": 8,
	"endLineNumber": 736,
	"endColumn": 17,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 736,
	"startColumn": 151,
	"endLineNumber": 736,
	"endColumn": 152,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "2741",
	"severity": 8,
	"message": "Property 'required' is missing in type '{ label: string; placeholder: string; value: string; onChange: (v: any) => void; }' but required in type '{ label: any; required: any; placeholder: any; value: any; onChange: any; type?: string | undefined; }'.",
	"source": "ts",
	"startLineNumber": 737,
	"startColumn": 8,
	"endLineNumber": 737,
	"endColumn": 17,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 737,
	"startColumn": 130,
	"endLineNumber": 737,
	"endColumn": 131,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type 'string' is not assignable to parameter of type 'never'.",
	"source": "ts",
	"startLineNumber": 742,
	"startColumn": 63,
	"endLineNumber": 742,
	"endColumn": 67,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "2739",
	"severity": 8,
	"message": "Type '{ label: string; placeholder: string; value: string; onChange: (v: any) => void; rows: number; }' is missing the following properties from type '{ label: any; required: any; placeholder: any; value: any; onChange: any; rows?: number | undefined; hint: any; }': required, hint",
	"source": "ts",
	"startLineNumber": 854,
	"startColumn": 10,
	"endLineNumber": 854,
	"endColumn": 18,
	"modelVersionId": 10,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/stark/Desktop/vektorlabs-all-kings/vektorlabs-fresh/app/generate/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 855,
	"startColumn": 54,
	"endLineNumber": 855,
	"endColumn": 55,
	"modelVersionId": 10,
	"origin": "extHost1"
}]
