// /lib/ai/all-sections.ts - Complete Section Library
// 100 total section variations (15 heroes + 85 other sections)

export const ALL_SECTIONS = {
  services: {
    bentoGrid: `<section class="section services" id="services"><div class="container"><div class="section-header text-center reveal"><span class="section-label">[LABEL]</span><h2>[TITLE]</h2></div><div class="bento-grid stagger"><div class="bento-card bento-lg"><div class="bento-icon">[ICON]</div><h3>[SERVICE_1]</h3><p>[DESC_1]</p></div><div class="bento-card"><h3>[SERVICE_2]</h3><p>[DESC_2]</p></div><div class="bento-card"><h3>[SERVICE_3]</h3><p>[DESC_3]</p></div><div class="bento-card bento-wide"><h3>[SERVICE_4]</h3><p>[DESC_4]</p></div><div class="bento-card"><h3>[SERVICE_5]</h3><p>[DESC_5]</p></div><div class="bento-card"><h3>[SERVICE_6]</h3><p>[DESC_6]</p></div></div></div></section>`,
    iconCards: `<section class="section services" id="services"><div class="container"><div class="section-header text-center reveal"><h2>[TITLE]</h2></div><div class="services-grid stagger"><div class="service-card"><div class="service-icon">[ICON_1]</div><h3>[SERVICE_1]</h3><p>[DESC_1]</p></div><div class="service-card"><div class="service-icon">[ICON_2]</div><h3>[SERVICE_2]</h3><p>[DESC_2]</p></div><div class="service-card"><div class="service-icon">[ICON_3]</div><h3>[SERVICE_3]</h3><p>[DESC_3]</p></div><div class="service-card"><div class="service-icon">[ICON_4]</div><h3>[SERVICE_4]</h3><p>[DESC_4]</p></div></div></div></section>`,
    alternatingRows: `<section class="section services" id="services"><div class="container"><div class="service-row reveal"><div class="service-content"><span class="service-num">01</span><h3>[SERVICE_1]</h3><p>[DESC_1]</p></div><div class="service-image"><img src="[IMG_1]" alt=""></div></div><div class="service-row reverse reveal"><div class="service-content"><span class="service-num">02</span><h3>[SERVICE_2]</h3><p>[DESC_2]</p></div><div class="service-image"><img src="[IMG_2]" alt=""></div></div></div></section>`,
    tabs: `<section class="section services" id="services"><div class="container"><div class="section-header text-center reveal"><h2>[TITLE]</h2></div><div class="tabs-wrapper" data-tabs><div class="tabs-nav"><button class="tab-btn active" data-tab="t1">[TAB_1]</button><button class="tab-btn" data-tab="t2">[TAB_2]</button><button class="tab-btn" data-tab="t3">[TAB_3]</button></div><div class="tab-panel active" data-tab-panel="t1"><div class="tab-content"><h3>[TITLE_1]</h3><p>[DESC_1]</p></div></div></div></div></section>`,
    processSteps: `<section class="section process" id="process"><div class="container"><div class="section-header text-center reveal"><h2>[TITLE]</h2></div><div class="process-timeline"><div class="process-step reveal"><div class="step-num">1</div><div class="step-content"><h3>[STEP_1]</h3><p>[DESC_1]</p></div></div><div class="process-step reveal"><div class="step-num">2</div><div class="step-content"><h3>[STEP_2]</h3><p>[DESC_2]</p></div></div><div class="process-step reveal"><div class="step-num">3</div><div class="step-content"><h3>[STEP_3]</h3><p>[DESC_3]</p></div></div></div></div></section>`,
    hoverCards: `<section class="section services" id="services"><div class="container"><div class="hover-grid stagger"><div class="hover-card"><div class="hover-bg" style="background-image:url('[IMG_1]')"></div><div class="hover-content"><h3>[SERVICE_1]</h3><p>[DESC_1]</p></div></div><div class="hover-card"><div class="hover-bg" style="background-image:url('[IMG_2]')"></div><div class="hover-content"><h3>[SERVICE_2]</h3><p>[DESC_2]</p></div></div><div class="hover-card"><div class="hover-bg" style="background-image:url('[IMG_3]')"></div><div class="hover-content"><h3>[SERVICE_3]</h3><p>[DESC_3]</p></div></div></div></div></section>`,
    featureList: `<section class="section features" id="features"><div class="container"><div class="features-grid"><div class="features-content reveal"><h2>[TITLE]</h2><p>[DESC]</p><ul class="features-list"><li><span>✓</span><div><strong>[F1]</strong><p>[D1]</p></div></li><li><span>✓</span><div><strong>[F2]</strong><p>[D2]</p></div></li></ul></div><div class="features-image reveal"><img src="[IMAGE]" alt=""></div></div></div></section>`,
    masonry: `<section class="section services" id="services"><div class="container"><div class="masonry-grid stagger"><div class="masonry-item tall"><img src="[IMG_1]" alt=""><div class="masonry-overlay"><h3>[S1]</h3></div></div><div class="masonry-item"><img src="[IMG_2]" alt=""><div class="masonry-overlay"><h3>[S2]</h3></div></div><div class="masonry-item"><img src="[IMG_3]" alt=""><div class="masonry-overlay"><h3>[S3]</h3></div></div></div></div></section>`,
    accordion: `<section class="section services" id="services"><div class="container"><div class="accordion-layout"><div class="accordion-content reveal"><h2>[TITLE]</h2></div><div class="accordion-list reveal" data-accordion="single"><div class="accordion-item open" data-accordion-item><button class="accordion-trigger">[S1]</button><div class="accordion-panel"><div>[D1]</div></div></div><div class="accordion-item" data-accordion-item><button class="accordion-trigger">[S2]</button><div class="accordion-panel"><div>[D2]</div></div></div></div></div></div></section>`,
    comparison: `<section class="section services" id="services"><div class="container"><div class="comparison-table reveal"><div class="comparison-header"><div></div><div class="comparison-us"><strong>[COMPANY]</strong></div><div class="comparison-them">Others</div></div><div class="comparison-row"><div>[F1]</div><div class="comparison-us">✓</div><div class="comparison-them">✗</div></div><div class="comparison-row"><div>[F2]</div><div class="comparison-us">✓</div><div class="comparison-them">~</div></div></div></div></section>`,
    imageCards: `<section class="section services" id="services"><div class="container"><div class="image-cards-grid stagger"><div class="image-card"><img src="[IMG_1]" alt=""><div class="image-card-content"><h3>[S1]</h3><p>[D1]</p></div></div><div class="image-card"><img src="[IMG_2]" alt=""><div class="image-card-content"><h3>[S2]</h3><p>[D2]</p></div></div></div></div></section>`,
    minimalList: `<section class="section services" id="services"><div class="container container-sm"><div class="minimal-services stagger"><a href="#" class="minimal-service"><span class="service-num">01</span><span class="service-name">[S1]</span><span>→</span></a><a href="#" class="minimal-service"><span class="service-num">02</span><span class="service-name">[S2]</span><span>→</span></a><a href="#" class="minimal-service"><span class="service-num">03</span><span class="service-name">[S3]</span><span>→</span></a></div></div></section>`,
  },
  testimonials: {
    featuredSingle: `<section class="section testimonials" id="testimonials"><div class="container"><div class="testimonial-featured reveal"><blockquote>[TESTIMONIAL]</blockquote><div class="testimonial-author"><img src="[IMG]" alt=""><div><strong>[NAME]</strong><span>[TITLE]</span></div></div></div></div></section>`,
    grid: `<section class="section testimonials" id="testimonials"><div class="container"><div class="testimonials-grid stagger"><div class="testimonial-card"><div class="stars">★★★★★</div><p>"[TEXT_1]"</p><div class="author"><img src="[IMG_1]" alt=""><div><strong>[NAME_1]</strong><span>[TITLE_1]</span></div></div></div><div class="testimonial-card"><div class="stars">★★★★★</div><p>"[TEXT_2]"</p><div class="author"><img src="[IMG_2]" alt=""><div><strong>[NAME_2]</strong><span>[TITLE_2]</span></div></div></div><div class="testimonial-card"><div class="stars">★★★★★</div><p>"[TEXT_3]"</p><div class="author"><img src="[IMG_3]" alt=""><div><strong>[NAME_3]</strong><span>[TITLE_3]</span></div></div></div></div></div></section>`,
    slider: `<section class="section testimonials" id="testimonials"><div class="container"><div class="testimonial-slider reveal" data-slider><div class="slider-track"><div class="testimonial-slide active"><blockquote>"[TEXT]"</blockquote><div class="author"><img src="[IMG]" alt=""><div><strong>[NAME]</strong><span>[TITLE]</span></div></div></div></div><div class="slider-nav"><button class="slider-prev" data-prev>←</button><button class="slider-next" data-next>→</button></div></div></div></section>`,
    masonry: `<section class="section testimonials" id="testimonials"><div class="container"><div class="testimonials-masonry stagger"><div class="testimonial-card tall"><p>"[LONG]"</p><strong>— [NAME_1]</strong></div><div class="testimonial-card"><p>"[SHORT]"</p><strong>— [NAME_2]</strong></div><div class="testimonial-card"><p>"[MED]"</p><strong>— [NAME_3]</strong></div></div></div></section>`,
    video: `<section class="section testimonials" id="testimonials"><div class="container"><div class="video-testimonials stagger"><div class="video-testimonial"><div class="video-thumb" style="background-image:url('[THUMB]')"><button class="play-btn">▶</button></div><div class="video-info"><strong>[NAME]</strong><span>[TITLE]</span></div></div></div></div></section>`,
    withLogos: `<section class="section testimonials" id="testimonials"><div class="container"><div class="client-logos reveal"><img src="[L1]" alt=""><img src="[L2]" alt=""><img src="[L3]" alt=""><img src="[L4]" alt=""></div><div class="testimonial-featured reveal"><blockquote>"[TEXT]"</blockquote><div class="author"><img src="[IMG]" alt=""><div><strong>[NAME]</strong><span>[TITLE]</span></div></div></div></div></section>`,
    cardStack: `<section class="section testimonials" id="testimonials"><div class="container"><div class="stack-layout"><div class="stack-content reveal"><h2>[TITLE]</h2><p>[DESC]</p></div><div class="card-stack reveal"><div class="stack-card"><p>"[T1]"</p><strong>— [N1]</strong></div><div class="stack-card"><p>"[T2]"</p><strong>— [N2]</strong></div></div></div></div></section>`,
    minimal: `<section class="section testimonials" id="testimonials"><div class="container container-sm"><div class="testimonial-minimal reveal"><blockquote class="big-testimonial">[TEXT]</blockquote><div class="minimal-author"><img src="[IMG]" alt=""><div><strong>[NAME]</strong><span>[TITLE]</span></div></div></div></div></section>`,
  },
  pricing: {
    threeTier: `<section class="section pricing" id="pricing"><div class="container"><div class="pricing-grid stagger"><div class="pricing-card"><h3>[P1]</h3><div class="price">$[M1]/mo</div><ul><li>✓ [F]</li></ul><a href="#" class="btn btn-outline btn-block">Get Started</a></div><div class="pricing-card featured"><div class="popular-badge">Most Popular</div><h3>[P2]</h3><div class="price">$[M2]/mo</div><ul><li>✓ [F]</li><li>✓ [F]</li></ul><a href="#" class="btn btn-primary btn-block">Get Started</a></div><div class="pricing-card"><h3>[P3]</h3><div class="price">$[M3]/mo</div><ul><li>✓ [F]</li><li>✓ [F]</li><li>✓ [F]</li></ul><a href="#" class="btn btn-outline btn-block">Get Started</a></div></div></div></section>`,
    comparison: `<section class="section pricing" id="pricing"><div class="container"><div class="pricing-table reveal"><table><thead><tr><th>Features</th><th>[P1]</th><th class="featured">[P2]</th><th>[P3]</th></tr></thead><tbody><tr><td>[F1]</td><td>✓</td><td class="featured">✓</td><td>✓</td></tr><tr><td>[F2]</td><td>-</td><td class="featured">✓</td><td>✓</td></tr></tbody></table></div></div></section>`,
    singleHighlight: `<section class="section pricing" id="pricing"><div class="container container-sm"><div class="pricing-single reveal"><h2>[TITLE]</h2><div class="pricing-amount"><span class="currency">$</span><span class="amount">[PRICE]</span></div><ul><li>✓ [F1]</li><li>✓ [F2]</li><li>✓ [F3]</li></ul><a href="#contact" class="btn btn-primary btn-lg btn-block">Get Started</a></div></div></section>`,
    withIcons: `<section class="section pricing" id="pricing"><div class="container"><div class="pricing-cards stagger"><div class="pricing-card"><div class="pricing-icon">[I1]</div><h3>[P1]</h3><div class="price">$[PR1]/mo</div><a href="#" class="btn btn-outline btn-block">Select</a></div><div class="pricing-card featured"><div class="pricing-icon">[I2]</div><h3>[P2]</h3><div class="price">$[PR2]/mo</div><a href="#" class="btn btn-primary btn-block">Select</a></div></div></div></section>`,
    horizontal: `<section class="section pricing" id="pricing"><div class="container"><div class="pricing-rows stagger"><div class="pricing-row"><div class="pricing-info"><h3>[P1]</h3><p>[D1]</p></div><div class="pricing-price">$[PR1]/mo</div><a href="#" class="btn btn-outline">Choose</a></div><div class="pricing-row featured"><span class="badge">Popular</span><div class="pricing-info"><h3>[P2]</h3><p>[D2]</p></div><div class="pricing-price">$[PR2]/mo</div><a href="#" class="btn btn-primary">Choose</a></div></div></div></section>`,
    enterprise: `<section class="section pricing" id="pricing"><div class="container"><div class="pricing-enterprise-grid"><div class="pricing-plans stagger"><div class="pricing-card"><h3>[P1]</h3><div class="price">$[PR1]/mo</div><a href="#" class="btn btn-outline btn-block">Choose</a></div><div class="pricing-card featured"><h3>[P2]</h3><div class="price">$[PR2]/mo</div><a href="#" class="btn btn-primary btn-block">Choose</a></div></div><div class="pricing-enterprise reveal"><h3>Enterprise</h3><p>[DESC]</p><a href="#contact" class="btn btn-lg btn-outline">Contact Sales</a></div></div></div></section>`,
  },
  cta: {
    gradient: `<section class="cta cta-gradient"><div class="container text-center reveal"><h2>[HEADLINE]</h2><p>[SUBHEADLINE]</p><div class="cta-buttons"><a href="#contact" class="btn btn-white btn-lg">[PRIMARY]</a><a href="#" class="btn btn-outline-white btn-lg">[SECONDARY]</a></div></div></section>`,
    withImage: `<section class="cta cta-image"><div class="container"><div class="cta-grid reveal"><div class="cta-content"><h2>[HEADLINE]</h2><p>[SUBHEADLINE]</p><a href="#contact" class="btn btn-primary btn-lg">[CTA]</a></div><div class="cta-image"><img src="[IMAGE]" alt=""></div></div></div></section>`,
    newsletter: `<section class="cta cta-newsletter"><div class="container container-sm"><div class="newsletter-box reveal"><h2>[HEADLINE]</h2><form class="newsletter-form" data-form><input type="email" placeholder="Your email" required><button type="submit" class="btn btn-primary">Subscribe</button></form></div></div></section>`,
    split: `<section class="cta cta-split"><div class="cta-left" style="background-image:url('[IMAGE]')"><div class="cta-overlay"></div><div class="cta-content reveal"><h2>[LEFT]</h2><a href="#" class="btn btn-white">[CTA]</a></div></div><div class="cta-right"><div class="cta-content reveal"><h2>[RIGHT]</h2><p>[DESC]</p><a href="#contact" class="btn btn-primary">[CTA]</a></div></div></section>`,
    minimal: `<section class="cta cta-minimal"><div class="container"><div class="cta-minimal-content reveal"><h2>[HEADLINE]</h2><a href="#contact" class="btn btn-primary btn-lg">[CTA] →</a></div></div></section>`,
    withStats: `<section class="cta cta-stats"><div class="container"><div class="cta-stats-grid reveal"><div class="cta-content"><h2>[HEADLINE]</h2><a href="#contact" class="btn btn-primary btn-lg">[CTA]</a></div><div class="cta-stats-row"><div class="stat"><span class="stat-number">[NUM_1]</span><span class="stat-label">[L1]</span></div><div class="stat"><span class="stat-number">[NUM_2]</span><span class="stat-label">[L2]</span></div></div></div></div></section>`,
    floatingCard: `<section class="cta cta-floating"><div class="container"><div class="cta-card glass reveal"><div class="cta-card-content"><h2>[HEADLINE]</h2><p>[SUBHEADLINE]</p></div><a href="#contact" class="btn btn-primary btn-lg">[CTA]</a></div></div></section>`,
    fullImage: `<section class="cta cta-full-image" style="background-image:url('[IMAGE]')"><div class="cta-overlay"></div><div class="container text-center reveal"><h2>[HEADLINE]</h2><a href="#contact" class="btn btn-white btn-lg">[CTA]</a></div></section>`,
    appDownload: `<section class="cta cta-app"><div class="container"><div class="cta-app-grid reveal"><div class="cta-content"><h2>[HEADLINE]</h2><p>[SUBHEADLINE]</p><div class="app-buttons"><a href="#" class="app-btn">App Store</a><a href="#" class="app-btn">Google Play</a></div></div><div class="cta-phone"><img src="[PHONE_IMAGE]" alt=""></div></div></div></section>`,
    countdown: `<section class="cta cta-countdown"><div class="container text-center reveal"><span class="cta-badge">[BADGE]</span><h2>[HEADLINE]</h2><div class="countdown" data-countdown="[DATE]"><div class="countdown-item"><span data-days>00</span><span>Days</span></div><div class="countdown-item"><span data-hours>00</span><span>Hours</span></div></div><a href="#contact" class="btn btn-primary btn-lg">[CTA]</a></div></section>`,
  },
  footer: {
    full: `<footer class="footer"><div class="container"><div class="footer-grid"><div class="footer-brand"><a href="#" class="footer-logo">[LOGO]</a><p>[TAGLINE]</p><div class="footer-social"><a href="#">FB</a><a href="#">IG</a><a href="#">TW</a></div></div><div class="footer-links"><h4>Company</h4><ul><li><a href="#">About</a></li><li><a href="#">Careers</a></li></ul></div><div class="footer-links"><h4>Services</h4><ul><li><a href="#">[S1]</a></li><li><a href="#">[S2]</a></li></ul></div><div class="footer-contact"><h4>Contact</h4><p>[ADDRESS]</p><p>[PHONE]</p><p>[EMAIL]</p></div></div><div class="footer-bottom"><p>© [YEAR] [COMPANY]</p><div class="footer-legal"><a href="#">Privacy</a><a href="#">Terms</a></div></div></div></footer>`,
    centered: `<footer class="footer footer-centered"><div class="container text-center"><a href="#" class="footer-logo">[LOGO]</a><nav class="footer-nav"><a href="#home">Home</a><a href="#about">About</a><a href="#services">Services</a><a href="#contact">Contact</a></nav><div class="footer-social"><a href="#">FB</a><a href="#">IG</a><a href="#">TW</a></div><p>© [YEAR] [COMPANY]</p></div></footer>`,
    minimal: `<footer class="footer footer-minimal"><div class="container"><div class="footer-minimal-content"><p>© [YEAR] [COMPANY]</p><nav><a href="#">Privacy</a><a href="#">Terms</a></nav></div></div></footer>`,
    newsletter: `<footer class="footer"><div class="container"><div class="footer-newsletter-grid"><div class="footer-info"><a href="#" class="footer-logo">[LOGO]</a><p>[TAGLINE]</p></div><div class="footer-newsletter"><h4>Subscribe</h4><form data-form><input type="email" placeholder="Email"><button class="btn btn-primary">Subscribe</button></form></div></div><hr><div class="footer-bottom"><p>© [YEAR] [COMPANY]</p></div></div></footer>`,
    dark: `<footer class="footer footer-dark"><div class="container"><div class="footer-grid"><div class="footer-brand"><a href="#" class="footer-logo">[LOGO]</a><p>[TAGLINE]</p></div><div class="footer-links"><h4>Links</h4><ul><li><a href="#">About</a></li><li><a href="#">Services</a></li></ul></div><div class="footer-links"><h4>Legal</h4><ul><li><a href="#">Privacy</a></li><li><a href="#">Terms</a></li></ul></div></div><div class="footer-bottom"><p>© [YEAR] [COMPANY]</p></div></div></footer>`,
    withCta: `<footer class="footer"><div class="footer-cta"><div class="container"><div class="footer-cta-content"><h3>[CTA_HEADLINE]</h3><a href="#contact" class="btn btn-white">[CTA]</a></div></div></div><div class="container"><div class="footer-main"><a href="#" class="footer-logo">[LOGO]</a><nav><a href="#">About</a><a href="#">Services</a></nav></div><div class="footer-bottom"><p>© [YEAR] [COMPANY]</p></div></div></footer>`,
    mega: `<footer class="footer footer-mega"><div class="container"><div class="footer-mega-grid"><div class="footer-brand"><a href="#" class="footer-logo">[LOGO]</a><p>[TAGLINE]</p><p>[ADDRESS]</p></div><div class="footer-links"><h4>Company</h4><ul><li><a href="#">About</a></li><li><a href="#">Team</a></li></ul></div><div class="footer-links"><h4>Services</h4><ul><li><a href="#">[S1]</a></li><li><a href="#">[S2]</a></li></ul></div><div class="footer-links"><h4>Resources</h4><ul><li><a href="#">Blog</a></li><li><a href="#">Help</a></li></ul></div><div class="footer-links"><h4>Legal</h4><ul><li><a href="#">Privacy</a></li><li><a href="#">Terms</a></li></ul></div></div><div class="footer-bottom"><p>© [YEAR] [COMPANY]</p><div class="footer-social"><a href="#">FB</a><a href="#">IG</a><a href="#">TW</a><a href="#">LI</a></div></div></div></footer>`,
    simple: `<footer class="footer footer-simple"><div class="container"><div class="footer-simple-content"><a href="#" class="footer-logo">[LOGO]</a><div class="footer-social"><a href="#">FB</a><a href="#">IG</a><a href="#">TW</a></div><p>© [YEAR] [COMPANY] · <a href="#">Privacy</a> · <a href="#">Terms</a></p></div></div></footer>`,
  },
  contact: {
    split: `<section class="section contact" id="contact"><div class="container"><div class="contact-grid"><div class="contact-info reveal"><h2>[TITLE]</h2><p>[DESC]</p><div class="contact-details"><div class="contact-item"><span>✉</span><div><strong>Email</strong><p>[EMAIL]</p></div></div><div class="contact-item"><span>☎</span><div><strong>Phone</strong><p>[PHONE]</p></div></div><div class="contact-item"><span>📍</span><div><strong>Address</strong><p>[ADDRESS]</p></div></div></div></div><div class="contact-form-wrapper reveal"><form class="contact-form" data-form><div class="form-row"><div class="form-group"><label>Name</label><input type="text" name="name" required></div><div class="form-group"><label>Email</label><input type="email" name="email" required></div></div><div class="form-group"><label>Message</label><textarea name="message" rows="5" required></textarea></div><button type="submit" class="btn btn-primary btn-lg btn-block">Send Message</button></form></div></div></div></section>`,
    centered: `<section class="section contact" id="contact"><div class="container container-sm"><div class="section-header text-center reveal"><h2>[TITLE]</h2><p>[DESC]</p></div><form class="contact-form reveal" data-form><div class="form-row"><div class="form-group"><input type="text" name="name" placeholder="Name" required></div><div class="form-group"><input type="email" name="email" placeholder="Email" required></div></div><div class="form-group"><textarea name="message" placeholder="Message" rows="6" required></textarea></div><button type="submit" class="btn btn-primary btn-lg">Send Message</button></form></div></section>`,
    withMap: `<section class="section contact" id="contact"><div class="contact-map-layout"><div class="contact-map"><iframe src="[GOOGLE_MAPS_EMBED]" width="100%" height="100%" frameborder="0" allowfullscreen loading="lazy"></iframe></div><div class="contact-content reveal"><h2>[TITLE]</h2><form class="contact-form" data-form><div class="form-group"><input type="text" name="name" placeholder="Name" required></div><div class="form-group"><input type="email" name="email" placeholder="Email" required></div><div class="form-group"><textarea name="message" placeholder="Message" rows="4" required></textarea></div><button type="submit" class="btn btn-primary btn-block">Send</button></form></div></div></section>`,
    cards: `<section class="section contact" id="contact"><div class="container"><div class="section-header text-center reveal"><h2>[TITLE]</h2></div><div class="contact-cards stagger"><div class="contact-card"><span class="card-icon">✉</span><h3>Email Us</h3><p>[EMAIL]</p><a href="mailto:[EMAIL]" class="btn btn-outline">Send Email</a></div><div class="contact-card"><span class="card-icon">☎</span><h3>Call Us</h3><p>[PHONE]</p><a href="tel:[PHONE]" class="btn btn-outline">Call Now</a></div><div class="contact-card"><span class="card-icon">📍</span><h3>Visit Us</h3><p>[ADDRESS]</p><a href="#" class="btn btn-outline">Directions</a></div></div></div></section>`,
    minimal: `<section class="section contact" id="contact"><div class="container container-sm"><div class="contact-minimal reveal"><h2>[TITLE]</h2><p class="contact-email"><a href="mailto:[EMAIL]">[EMAIL]</a></p><p class="contact-phone"><a href="tel:[PHONE]">[PHONE]</a></p></div></div></section>`,
    fullWidth: `<section class="contact-full" style="background-image:url('[BG_IMAGE]')"><div class="contact-overlay"></div><div class="container text-center reveal"><h2>[TITLE]</h2><p>[DESC]</p><div class="contact-info-row"><div class="info-item"><strong>Email</strong><p>[EMAIL]</p></div><div class="info-item"><strong>Phone</strong><p>[PHONE]</p></div><div class="info-item"><strong>Address</strong><p>[ADDRESS]</p></div></div><a href="mailto:[EMAIL]" class="btn btn-white btn-lg">Get In Touch</a></div></section>`,
  },
  team: {
    grid: `<section class="section team" id="team"><div class="container"><div class="section-header text-center reveal"><h2>[TITLE]</h2></div><div class="team-grid stagger"><div class="team-card"><div class="team-image"><img src="[IMG_1]" alt="[N1]"><div class="team-social"><a href="#">LI</a><a href="#">TW</a></div></div><h3>[N1]</h3><p>[T1]</p></div><div class="team-card"><div class="team-image"><img src="[IMG_2]" alt="[N2]"><div class="team-social"><a href="#">LI</a><a href="#">TW</a></div></div><h3>[N2]</h3><p>[T2]</p></div><div class="team-card"><div class="team-image"><img src="[IMG_3]" alt="[N3]"><div class="team-social"><a href="#">LI</a><a href="#">TW</a></div></div><h3>[N3]</h3><p>[T3]</p></div><div class="team-card"><div class="team-image"><img src="[IMG_4]" alt="[N4]"><div class="team-social"><a href="#">LI</a><a href="#">TW</a></div></div><h3>[N4]</h3><p>[T4]</p></div></div></div></section>`,
    withBio: `<section class="section team" id="team"><div class="container"><div class="team-bio-grid stagger"><div class="team-bio-card"><img src="[IMG_1]" alt=""><div class="team-bio-content"><h3>[N1]</h3><p class="team-role">[T1]</p><p class="team-bio">[BIO_1]</p></div></div><div class="team-bio-card"><img src="[IMG_2]" alt=""><div class="team-bio-content"><h3>[N2]</h3><p class="team-role">[T2]</p><p class="team-bio">[BIO_2]</p></div></div></div></div></section>`,
    carousel: `<section class="section team" id="team"><div class="container"><div class="section-header text-center reveal"><h2>[TITLE]</h2></div><div class="team-carousel reveal" data-slider><div class="carousel-track"><div class="team-slide"><img src="[IMG_1]" alt=""><h3>[N1]</h3><p>[T1]</p></div><div class="team-slide"><img src="[IMG_2]" alt=""><h3>[N2]</h3><p>[T2]</p></div><div class="team-slide"><img src="[IMG_3]" alt=""><h3>[N3]</h3><p>[T3]</p></div></div></div></div></section>`,
    minimal: `<section class="section team" id="team"><div class="container container-sm"><div class="section-header reveal"><h2>[TITLE]</h2></div><div class="team-minimal stagger"><div class="team-row"><img src="[IMG_1]" alt=""><div><strong>[N1]</strong><span>[T1]</span></div></div><div class="team-row"><img src="[IMG_2]" alt=""><div><strong>[N2]</strong><span>[T2]</span></div></div><div class="team-row"><img src="[IMG_3]" alt=""><div><strong>[N3]</strong><span>[T3]</span></div></div></div></div></section>`,
    featured: `<section class="section team" id="team"><div class="container"><div class="team-featured reveal"><div class="team-featured-image"><img src="[FEATURED_IMG]" alt=""></div><div class="team-featured-content"><span class="section-label">[LABEL]</span><h2>[FEATURED_NAME]</h2><p class="team-role">[FEATURED_TITLE]</p><p class="team-bio">[FEATURED_BIO]</p></div></div><div class="team-grid-sm stagger"><div class="team-card-sm"><img src="[IMG_1]" alt=""><h4>[N1]</h4><p>[T1]</p></div><div class="team-card-sm"><img src="[IMG_2]" alt=""><h4>[N2]</h4><p>[T2]</p></div><div class="team-card-sm"><img src="[IMG_3]" alt=""><h4>[N3]</h4><p>[T3]</p></div></div></div></section>`,
  },
  gallery: {
    grid: `<section class="section gallery" id="gallery"><div class="container"><div class="section-header text-center reveal"><h2>[TITLE]</h2></div><div class="gallery-grid stagger"><div class="gallery-item" data-lightbox><img src="[IMG_1]" alt="" loading="lazy"></div><div class="gallery-item" data-lightbox><img src="[IMG_2]" alt="" loading="lazy"></div><div class="gallery-item" data-lightbox><img src="[IMG_3]" alt="" loading="lazy"></div><div class="gallery-item" data-lightbox><img src="[IMG_4]" alt="" loading="lazy"></div><div class="gallery-item" data-lightbox><img src="[IMG_5]" alt="" loading="lazy"></div><div class="gallery-item" data-lightbox><img src="[IMG_6]" alt="" loading="lazy"></div></div></div></section>`,
    masonry: `<section class="section gallery" id="gallery"><div class="container"><div class="gallery-masonry stagger"><div class="gallery-item tall" data-lightbox><img src="[IMG_1]" alt=""></div><div class="gallery-item" data-lightbox><img src="[IMG_2]" alt=""></div><div class="gallery-item" data-lightbox><img src="[IMG_3]" alt=""></div><div class="gallery-item tall" data-lightbox><img src="[IMG_4]" alt=""></div><div class="gallery-item" data-lightbox><img src="[IMG_5]" alt=""></div></div></div></section>`,
    filterable: `<section class="section gallery" id="gallery"><div class="container"><div class="gallery-filters reveal"><button class="filter-btn active" data-filter="all">All</button><button class="filter-btn" data-filter="[CAT_1]">[CAT_1]</button><button class="filter-btn" data-filter="[CAT_2]">[CAT_2]</button></div><div class="gallery-grid filterable stagger"><div class="gallery-item" data-category="[CAT_1]"><img src="[IMG_1]" alt=""></div><div class="gallery-item" data-category="[CAT_2]"><img src="[IMG_2]" alt=""></div><div class="gallery-item" data-category="[CAT_1]"><img src="[IMG_3]" alt=""></div></div></div></section>`,
    carousel: `<section class="section gallery" id="gallery"><div class="container"><div class="gallery-carousel reveal" data-slider><div class="carousel-track"><div class="carousel-slide"><img src="[IMG_1]" alt=""></div><div class="carousel-slide"><img src="[IMG_2]" alt=""></div><div class="carousel-slide"><img src="[IMG_3]" alt=""></div></div><button class="carousel-prev" data-prev>←</button><button class="carousel-next" data-next>→</button></div></div></section>`,
    fullWidth: `<section class="gallery-full"><div class="gallery-scroll"><div class="gallery-item"><img src="[IMG_1]" alt=""></div><div class="gallery-item"><img src="[IMG_2]" alt=""></div><div class="gallery-item"><img src="[IMG_3]" alt=""></div><div class="gallery-item"><img src="[IMG_4]" alt=""></div><div class="gallery-item"><img src="[IMG_5]" alt=""></div></div></section>`,
    withCaptions: `<section class="section gallery" id="gallery"><div class="container"><div class="gallery-grid stagger"><div class="gallery-item-caption"><img src="[IMG_1]" alt=""><div class="caption"><h4>[C1]</h4><p>[D1]</p></div></div><div class="gallery-item-caption"><img src="[IMG_2]" alt=""><div class="caption"><h4>[C2]</h4><p>[D2]</p></div></div><div class="gallery-item-caption"><img src="[IMG_3]" alt=""><div class="caption"><h4>[C3]</h4><p>[D3]</p></div></div></div></div></section>`,
  },
  stats: {
    simpleRow: `<section class="section stats"><div class="container"><div class="stats-row reveal"><div class="stat"><span class="stat-number" data-count="[NUM_1]">0</span><span class="stat-suffix">[S1]</span><span class="stat-label">[L1]</span></div><div class="stat"><span class="stat-number" data-count="[NUM_2]">0</span><span class="stat-suffix">[S2]</span><span class="stat-label">[L2]</span></div><div class="stat"><span class="stat-number" data-count="[NUM_3]">0</span><span class="stat-suffix">[S3]</span><span class="stat-label">[L3]</span></div><div class="stat"><span class="stat-number" data-count="[NUM_4]">0</span><span class="stat-suffix">[S4]</span><span class="stat-label">[L4]</span></div></div></div></section>`,
    withBackground: `<section class="stats-bg" style="background-image:url('[BG_IMAGE]')"><div class="stats-overlay"></div><div class="container"><div class="stats-row reveal"><div class="stat"><span class="stat-number">[NUM_1][S1]</span><span class="stat-label">[L1]</span></div><div class="stat"><span class="stat-number">[NUM_2][S2]</span><span class="stat-label">[L2]</span></div><div class="stat"><span class="stat-number">[NUM_3][S3]</span><span class="stat-label">[L3]</span></div></div></div></section>`,
    cards: `<section class="section stats"><div class="container"><div class="stats-cards stagger"><div class="stat-card"><span class="stat-icon">[I1]</span><span class="stat-number">[NUM_1][S1]</span><span class="stat-label">[L1]</span></div><div class="stat-card"><span class="stat-icon">[I2]</span><span class="stat-number">[NUM_2][S2]</span><span class="stat-label">[L2]</span></div><div class="stat-card"><span class="stat-icon">[I3]</span><span class="stat-number">[NUM_3][S3]</span><span class="stat-label">[L3]</span></div><div class="stat-card"><span class="stat-icon">[I4]</span><span class="stat-number">[NUM_4][S4]</span><span class="stat-label">[L4]</span></div></div></div></section>`,
    withContent: `<section class="section stats"><div class="container"><div class="stats-content-grid"><div class="stats-content reveal"><h2>[TITLE]</h2><p>[DESC]</p><a href="#contact" class="btn btn-primary btn-lg">[CTA]</a></div><div class="stats-grid reveal"><div class="stat"><span class="stat-number">[NUM_1][S1]</span><span class="stat-label">[L1]</span></div><div class="stat"><span class="stat-number">[NUM_2][S2]</span><span class="stat-label">[L2]</span></div><div class="stat"><span class="stat-number">[NUM_3][S3]</span><span class="stat-label">[L3]</span></div><div class="stat"><span class="stat-number">[NUM_4][S4]</span><span class="stat-label">[L4]</span></div></div></div></div></section>`,
  },
  blog: {
    grid: `<section class="section blog" id="blog"><div class="container"><div class="section-header text-center reveal"><h2>[TITLE]</h2></div><div class="blog-grid stagger"><article class="blog-card"><div class="blog-image"><img src="[IMG_1]" alt=""><span class="blog-category">[CAT_1]</span></div><div class="blog-content"><h3><a href="#">[T1]</a></h3><p>[E1]</p><div class="blog-meta"><span>[D1]</span><span>[R1]</span></div></div></article><article class="blog-card"><div class="blog-image"><img src="[IMG_2]" alt=""><span class="blog-category">[CAT_2]</span></div><div class="blog-content"><h3><a href="#">[T2]</a></h3><p>[E2]</p><div class="blog-meta"><span>[D2]</span><span>[R2]</span></div></div></article><article class="blog-card"><div class="blog-image"><img src="[IMG_3]" alt=""><span class="blog-category">[CAT_3]</span></div><div class="blog-content"><h3><a href="#">[T3]</a></h3><p>[E3]</p><div class="blog-meta"><span>[D3]</span><span>[R3]</span></div></div></article></div></div></section>`,
    featuredList: `<section class="section blog" id="blog"><div class="container"><div class="blog-featured-layout"><article class="blog-featured reveal"><img src="[FEATURED_IMG]" alt=""><div class="blog-content"><span class="blog-category">[FEATURED_CAT]</span><h3>[FEATURED_TITLE]</h3><p>[FEATURED_EXCERPT]</p><a href="#" class="btn btn-primary">Read More</a></div></article><div class="blog-list stagger"><article class="blog-list-item"><img src="[IMG_1]" alt=""><div><h4>[T1]</h4><span class="blog-date">[D1]</span></div></article><article class="blog-list-item"><img src="[IMG_2]" alt=""><div><h4>[T2]</h4><span class="blog-date">[D2]</span></div></article></div></div></div></section>`,
    minimal: `<section class="section blog" id="blog"><div class="container container-sm"><div class="section-header reveal"><h2>[TITLE]</h2></div><div class="blog-minimal stagger"><article class="blog-minimal-item"><span class="blog-date">[D1]</span><h3><a href="#">[T1]</a></h3><p>[E1]</p></article><article class="blog-minimal-item"><span class="blog-date">[D2]</span><h3><a href="#">[T2]</a></h3><p>[E2]</p></article></div></div></section>`,
    cardsRow: `<section class="section blog" id="blog"><div class="container"><div class="section-header-row reveal"><h2>[TITLE]</h2><a href="#" class="btn btn-outline">View All</a></div><div class="blog-row stagger"><article class="blog-card-horizontal"><img src="[IMG_1]" alt=""><div class="blog-content"><span class="blog-category">[CAT_1]</span><h3>[T1]</h3><span class="blog-date">[D1]</span></div></article><article class="blog-card-horizontal"><img src="[IMG_2]" alt=""><div class="blog-content"><span class="blog-category">[CAT_2]</span><h3>[T2]</h3><span class="blog-date">[D2]</span></div></article></div></div></section>`,
  },
  portfolio: {
    grid: `<section class="section portfolio" id="work"><div class="container"><div class="section-header text-center reveal"><h2>[TITLE]</h2></div><div class="portfolio-grid stagger"><div class="portfolio-item"><img src="[IMG_1]" alt=""><div class="portfolio-overlay"><h3>[P1]</h3><p>[C1]</p><a href="#" class="btn btn-sm btn-white">View</a></div></div><div class="portfolio-item"><img src="[IMG_2]" alt=""><div class="portfolio-overlay"><h3>[P2]</h3><p>[C2]</p><a href="#" class="btn btn-sm btn-white">View</a></div></div><div class="portfolio-item"><img src="[IMG_3]" alt=""><div class="portfolio-overlay"><h3>[P3]</h3><p>[C3]</p><a href="#" class="btn btn-sm btn-white">View</a></div></div><div class="portfolio-item"><img src="[IMG_4]" alt=""><div class="portfolio-overlay"><h3>[P4]</h3><p>[C4]</p><a href="#" class="btn btn-sm btn-white">View</a></div></div></div></div></section>`,
    filterable: `<section class="section portfolio" id="work"><div class="container"><div class="portfolio-filters reveal"><button class="filter-btn active" data-filter="all">All</button><button class="filter-btn" data-filter="[CAT_1]">[CAT_1]</button><button class="filter-btn" data-filter="[CAT_2]">[CAT_2]</button></div><div class="portfolio-grid filterable stagger"><div class="portfolio-item" data-category="[CAT_1]"><img src="[IMG_1]" alt=""><div class="portfolio-info"><h3>[T1]</h3></div></div><div class="portfolio-item" data-category="[CAT_2]"><img src="[IMG_2]" alt=""><div class="portfolio-info"><h3>[T2]</h3></div></div></div></div></section>`,
    caseStudies: `<section class="section portfolio" id="work"><div class="container"><div class="case-studies"><div class="case-study reveal"><div class="case-image"><img src="[IMG_1]" alt=""></div><div class="case-content"><span class="case-category">[C1]</span><h3>[P1]</h3><p>[D1]</p><a href="#" class="link-arrow">View Case Study →</a></div></div><div class="case-study reverse reveal"><div class="case-image"><img src="[IMG_2]" alt=""></div><div class="case-content"><span class="case-category">[C2]</span><h3>[P2]</h3><p>[D2]</p><a href="#" class="link-arrow">View Case Study →</a></div></div></div></div></section>`,
    minimalList: `<section class="section portfolio" id="work"><div class="container container-sm"><div class="portfolio-list stagger"><a href="#" class="portfolio-list-item"><span class="project-name">[P1]</span><span class="project-year">[Y1]</span><span class="project-arrow">→</span></a><a href="#" class="portfolio-list-item"><span class="project-name">[P2]</span><span class="project-year">[Y2]</span><span class="project-arrow">→</span></a><a href="#" class="portfolio-list-item"><span class="project-name">[P3]</span><span class="project-year">[Y3]</span><span class="project-arrow">→</span></a></div></div></section>`,
    fullWidth: `<section class="portfolio-showcase"><div class="showcase-item" style="background-image:url('[IMG_1]')"><div class="showcase-content"><span>[C1]</span><h2>[P1]</h2><a href="#" class="btn btn-white">View</a></div></div><div class="showcase-item" style="background-image:url('[IMG_2]')"><div class="showcase-content"><span>[C2]</span><h2>[P2]</h2><a href="#" class="btn btn-white">View</a></div></div></section>`,
  },
  faq: {
    accordion: `<section class="section faq" id="faq"><div class="container"><div class="faq-layout"><div class="faq-header reveal"><h2>[TITLE]</h2><p>[DESC]</p></div><div class="faq-list reveal" data-accordion="single"><div class="faq-item open" data-accordion-item><button class="faq-question" data-accordion-trigger>[Q1]</button><div class="faq-answer" data-accordion-content><div>[A1]</div></div></div><div class="faq-item" data-accordion-item><button class="faq-question" data-accordion-trigger>[Q2]</button><div class="faq-answer" data-accordion-content><div>[A2]</div></div></div><div class="faq-item" data-accordion-item><button class="faq-question" data-accordion-trigger>[Q3]</button><div class="faq-answer" data-accordion-content><div>[A3]</div></div></div><div class="faq-item" data-accordion-item><button class="faq-question" data-accordion-trigger>[Q4]</button><div class="faq-answer" data-accordion-content><div>[A4]</div></div></div></div></div></div></section>`,
    twoColumns: `<section class="section faq" id="faq"><div class="container"><div class="section-header text-center reveal"><h2>[TITLE]</h2></div><div class="faq-columns stagger"><div class="faq-column"><div class="faq-simple"><h3>[Q1]</h3><p>[A1]</p></div><div class="faq-simple"><h3>[Q2]</h3><p>[A2]</p></div><div class="faq-simple"><h3>[Q3]</h3><p>[A3]</p></div></div><div class="faq-column"><div class="faq-simple"><h3>[Q4]</h3><p>[A4]</p></div><div class="faq-simple"><h3>[Q5]</h3><p>[A5]</p></div><div class="faq-simple"><h3>[Q6]</h3><p>[A6]</p></div></div></div></div></section>`,
    withContact: `<section class="section faq" id="faq"><div class="container"><div class="faq-contact-layout"><div class="faq-main reveal"><h2>[TITLE]</h2><div class="faq-list" data-accordion><div class="faq-item open" data-accordion-item><button class="faq-question" data-accordion-trigger>[Q1]</button><div class="faq-answer" data-accordion-content><div>[A1]</div></div></div><div class="faq-item" data-accordion-item><button class="faq-question" data-accordion-trigger>[Q2]</button><div class="faq-answer" data-accordion-content><div>[A2]</div></div></div></div></div><div class="faq-contact reveal"><h3>Still have questions?</h3><p>Our team is here to help.</p><a href="#contact" class="btn btn-primary btn-lg">Get In Touch</a></div></div></div></section>`,
  },
  nav: {
    standard: `<nav class="nav" id="nav"><div class="container"><a href="#" class="nav-logo">[LOGO]</a><ul class="nav-menu"><li><a href="#services">Services</a></li><li><a href="#about">About</a></li><li><a href="#testimonials">Testimonials</a></li><li><a href="#contact">Contact</a></li></ul><a href="#contact" class="btn btn-primary nav-cta">[CTA]</a><button class="nav-toggle" aria-label="Toggle menu"><span></span><span></span><span></span></button></div></nav>`,
    centered: `<nav class="nav nav-centered" id="nav"><div class="container"><ul class="nav-menu nav-left"><li><a href="#services">Services</a></li><li><a href="#about">About</a></li></ul><a href="#" class="nav-logo">[LOGO]</a><ul class="nav-menu nav-right"><li><a href="#testimonials">Testimonials</a></li><li><a href="#contact">Contact</a></li></ul><button class="nav-toggle" aria-label="Toggle menu"><span></span><span></span><span></span></button></div></nav>`,
    transparent: `<nav class="nav nav-transparent" id="nav"><div class="container"><a href="#" class="nav-logo">[LOGO]</a><ul class="nav-menu"><li><a href="#services">Services</a></li><li><a href="#about">About</a></li><li><a href="#contact">Contact</a></li></ul><a href="#contact" class="btn btn-outline-white nav-cta">[CTA]</a><button class="nav-toggle" aria-label="Toggle menu"><span></span><span></span><span></span></button></div></nav>`,
    minimal: `<nav class="nav nav-minimal" id="nav"><div class="container"><a href="#" class="nav-logo">[LOGO]</a><button class="nav-menu-btn" aria-label="Toggle menu">Menu</button></div></nav><div class="nav-fullscreen" data-nav-fullscreen><button class="nav-close" aria-label="Close menu">×</button><ul class="nav-fullscreen-menu"><li><a href="#home">Home</a></li><li><a href="#services">Services</a></li><li><a href="#about">About</a></li><li><a href="#contact">Contact</a></li></ul></div>`,
  },
  about: {
    split: `<section class="section about" id="about"><div class="container"><div class="about-grid"><div class="about-image reveal"><img src="[IMAGE]" alt="About Us"><div class="about-badge"><span class="badge-number">[YEARS]</span><span>Years</span></div></div><div class="about-content reveal"><h2>[TITLE]</h2><p class="about-lead">[LEAD]</p><p>[DESC]</p><div class="about-features"><div class="about-feature"><span class="feature-check">✓</span><div><strong>[F1]</strong><p>[D1]</p></div></div><div class="about-feature"><span class="feature-check">✓</span><div><strong>[F2]</strong><p>[D2]</p></div></div></div><a href="#contact" class="btn btn-primary btn-lg">[CTA]</a></div></div></div></section>`,
    story: `<section class="section about" id="about"><div class="container container-sm"><div class="about-story reveal"><h2>[TITLE]</h2><p class="about-lead">[LEAD]</p><div class="about-story-content"><p>[P1]</p><p>[P2]</p></div><div class="about-signature"><img src="[SIGNATURE]" alt=""><div><strong>[FOUNDER_NAME]</strong><span>[FOUNDER_TITLE]</span></div></div></div></div></section>`,
    missionVision: `<section class="section about" id="about"><div class="container"><div class="section-header text-center reveal"><h2>[TITLE]</h2></div><div class="mv-grid stagger"><div class="mv-card"><span class="mv-icon">[I1]</span><h3>Our Mission</h3><p>[MISSION]</p></div><div class="mv-card"><span class="mv-icon">[I2]</span><h3>Our Vision</h3><p>[VISION]</p></div><div class="mv-card"><span class="mv-icon">[I3]</span><h3>Our Values</h3><p>[VALUES]</p></div></div></div></section>`,
    timeline: `<section class="section about" id="about"><div class="container"><div class="section-header text-center reveal"><h2>[TITLE]</h2></div><div class="timeline"><div class="timeline-line"></div><div class="timeline-item reveal"><div class="timeline-year">[Y1]</div><div class="timeline-content"><h3>[E1]</h3><p>[D1]</p></div></div><div class="timeline-item reveal"><div class="timeline-year">[Y2]</div><div class="timeline-content"><h3>[E2]</h3><p>[D2]</p></div></div><div class="timeline-item reveal"><div class="timeline-year">[Y3]</div><div class="timeline-content"><h3>[E3]</h3><p>[D3]</p></div></div></div></div></section>`,
  },
};

// Helper functions
export function getSection(category: keyof typeof ALL_SECTIONS, type: string): string {
  const cat = ALL_SECTIONS[category];
  if (!cat) return '';
  return (cat as Record<string, string>)[type] || Object.values(cat)[0] || '';
}
export function getSectionTypes(category: keyof typeof ALL_SECTIONS): string[] { return Object.keys(ALL_SECTIONS[category] || {}); }
export function getTotalSectionCount(): number { let t = 0; for (const c of Object.keys(ALL_SECTIONS)) { t += Object.keys((ALL_SECTIONS as any)[c]).length; } return t; }
export function getCategoryCounts(): Record<string, number> { const c: Record<string, number> = {}; for (const k of Object.keys(ALL_SECTIONS)) { c[k] = Object.keys((ALL_SECTIONS as any)[k]).length; } return c; }
// services(12)+testimonials(8)+pricing(6)+cta(10)+footer(8)+contact(6)+team(5)+gallery(6)+stats(4)+blog(4)+portfolio(5)+faq(3)+nav(4)+about(4)=85 + 15 heroes = 100 total!
